blank_issues_enabled: false
contact_links:
  - name: 💬 সাধারণ প্রশ্ন
    url: https://github.com/hitawhidme/TDP-Tawhid-Downloader-Pro/discussions
    about: বাগ বা ফিচার না হলে, সাধারণ প্রশ্নের জন্য Discussions ব্যবহার করুন
